#!/usr/bin/env python

import fetch
import sys

FETCH_URL = "http://www.reddit.com/r/A858DE45F56D9BC9/.json"
EXPECT_FAIL = False

try:
	data = fetch.fetch(FETCH_URL)
	assert "data" in data, "Failed to fetch Subreddit: %s" % data

	if EXPECT_FAIL:
		print "Subreddit is back!"
except:
	if EXPECT_FAIL:
		sys.exit(0)
	else:
		raise

posts = data["data"]["children"]

for post in posts:
	fetch.save_post(post)

